### PR TITLE
Custom margin support

### PR DESCRIPTION
**Pull request by SergeySatskiy**

### CODE REVIEW

**Comment by hlamer** [comment]
Hi
Thank you for PR.
@SergeySatskiy, could you reformat the documentation as Sphinx and add a link to it on the main documentation page?
Now Qutepart documentation is automatically auto-generated from the sources and published on http://qutepart.readthedocs.io/en/latest/ Will be better if API uses can see all docs on 1 site.

**Comment by SergeySatskiy** [comment]
I have no experience with Sphinx so far and thus I don't really understand what you mean.
Do you mean to move the content of CustomMargins.md to the top of __init__.py and remove the CustomMargins.md file?

**Comment by hlamer** [comment]
No, not to `__init__.py`.
It is possible to include the documentation to [this file](https://raw.githubusercontent.com/hlamer/qutepart/master/doc/source/index.rst).
Would be even better if you created a .rst file in doc/ and added to index.rst a link to this file.

**Comment by SergeySatskiy** [comment]
Done. Please review the updates.

**Pull request merged**
